#!/bin/zsh

echo "Installing dot-files:\n"

# grab directory structure
_dir=$(dirname $(readlink -f $0))

# install oh-my-zsh if not installed
if [ ! -d ~/.oh-my-zsh ]; then
    echo "\t[+] Downloading oh-my-zsh...."
    wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh
fi

# Installation:

echo "\t[+] Creating soft-links to dot-files."

# vim
ln -sf $_dir/.vimrc ~
cp -r $_dir/.vim ~
# zsh
ln -sf $_dir/.zshrc ~
ln -sf $_dir/.zshenv ~
# tmux
ln -sf $_dir/.tmux.conf ~
# git
ln -sf $_dir/.gitconfig ~
# gdb
ln -sf $_dir/.gdbinit ~
# update script
ln -sf $_dir/update ~

# install vundle
if [ ! -d ~/.vim/bundle/vundle ]; then
    echo "\t[+] Installing vundle."
    git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle &> /dev/null
fi

echo "\t[+] Installing new vundles."
vim +PluginInstall +qall

echo "\t[+] Reloading zshrc with new config."
# execute zshrc to utilize new config
source ~/.zshrc
