#!/bin/bash

set -e

echo -e "Installing dot-files:"

# grab directory structure
_dir=$(pwd -P)

# Installation:

echo -e "\t[+] Creating soft-links to dot-files."

# vim
ln -sf $_dir/.vimrc ~
cp -r $_dir/.vim ~
# zsh
ln -sf $_dir/.zshrc ~
ln -sf $_dir/.zshenv ~
ln -sf $_dir/.zsh ~
# tmux
ln -sf $_dir/.tmux.conf ~
# git
ln -sf $_dir/.gitconfig ~
# gdb
ln -sf $_dir/.gdbinit ~
# update script (only for debian)
if [[ `uname -s` == "Linux" ]]; then ln -sf $_dir/update ~; fi

# install vundle
if [ ! -d ~/.vim/bundle/vundle ]; then
    echo -e "\t[+] Installing vundle."
    git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle &> /dev/null
fi

echo -e "\t[+] Installing new vundles."
vim +PluginInstall +qall

echo -e "Restart terminal session for changes to take effect."
