alias apt-get="sudo apt-get"
alias aptitude="sudo aptitude"
alias ifconfig="sudo ifconfig"
alias tmux="tmux -2"
alias ls="ls -A --color=always"
alias ll="ls -lA --color=always"
alias gdb="gdb --quiet"
alias grep="grep --color=always"
